apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: back-media
  name: back-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
