apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: back
  name: back
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    io.kompose.service: back

