apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: db
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c','rm -rf /var/lib/postgresql/data/lost+found']
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data        
      containers:
        - envFrom:
          - configMapRef:
              name: variables-env
          image: postgres:12-alpine
          name: taiga-db
          ports:
            - containerPort: 5432          
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
status: {}
