apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: events
  name: events
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: "3023"
      port: 3023
      targetPort: 3023
  type: ClusterIP
  selector:
    io.kompose.service: events

