apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: events
  name: events
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: events
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: events
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: variables-env
          ports:
          - containerPort: 8888
          - containerPort: 3023
          image: dokfish/taiga-events:6.3.1
          name: taiga-events
          resources: {}
      restartPolicy: Always
status: {}
