apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: front
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: variables-env
          image: dokfish/taiga-front:6.2.1
          ports:
          - containerPort: 80
          name: taiga-front
          resources: {}
          volumeMounts:
            - mountPath: /taiga-conf
              name: front-conf
      restartPolicy: Always
      volumes:
        - name: front-conf
          persistentVolumeClaim:
            claimName: front-conf
status: {}
