apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: proxy
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: variables-env
          image: dokfish/taiga-proxy:http-v1.2
          name: taiga-proxy
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /taiga-conf
              name: proxy-conf
      restartPolicy: Always
      volumes:
        - name: proxy-conf
          persistentVolumeClaim:
            claimName: proxy-conf
status: {}
