apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: proxy-conf
  name: proxy-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
