apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  type: ClusterIP
  selector:
    io.kompose.service: rabbit

