apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: events
  name: events
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: events
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: events
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: variables-env
          ports:
          - containerPort: 8888
          - containerPort: 3023
          image: dokfish/taiga-events:6.3
          name: taiga-events
          resources: {}
      restartPolicy: Always
status: {}
